### PR TITLE
refactor: put logging calls using chalk in their own functions in the…

### PR DESCRIPTION
**Pull request by LouisH-760**
…ir own module

This clears up quite a bit of duplicated code, and shouldn't break anything. Fully untested, so merge at your own risk. I also added brackets around ifs when i encountered it. There might be a few `;` missing, sorry.

### CODE REVIEW

**Comment by LouisH-760** [comment]
Potential further improvements: Some color for messages seem to always be the same (eg error is red). It would make sense to move that from the individual function calls to the function itself.

**Comment by LouisH-760** [comment]
Forgot to put in a variable yesterday, it passes checks now

**Review by GiorgioBrux — APPROVED** [review]

**Comment by GiorgioBrux** [comment]
Thanks!

**Pull request merged**
