### PR TITLE
Redeeming 'Xbox game codes'/'Payment source required'

### LINKED ISSUE #23: 'Payment source required to redeem gift'
'Payment source required to redeem gift' when redeeming some type of gifts.

### LINKED ISSUE #31: XBOX Games Codes?
Recently, I have often now already received the message that I need a payment method. Have also seen other Sniper programs that have a workaround.

Xbox codes can apparently not be redeemed on all accounts

`2021-01-12T18:40:45.844129+00:00 app[worker.1]: [Nitro Sniper] (ERROR) Tried to redeem code [3ytqzG7kAQYw6kM2xHpbPSat] but got error: Payment source required to redeem gift..`

The codes also seem to be longer

### PR DESCRIPTION
**Pull request by 7fe2752182d43f856b49a802e36d597c78ae87b**
Attempts to fix #23 and fix #31 .

Uses the mainToken to get payment_source_id and passes it along to the redeem request body. This adds a new module, sync-request. The [npm page](https://www.npmjs.com/package/sync-request) has a warning message about this package.

I tried using axios/phin unpromisifed/promisified to get the payment source id out of `(err, res) =>` and `.then((response) =>` but a variable defined inside the arrow function couldn't be accessed outside of the function. I decided against making a request to get the id every time a code is valid to save time.

I also tried to use async/await with the two http clients, but 'top level await' is only available on a specific node version or higher, and requires a special `--harmony-top-level-await` flag.

This PR may not be necessary if the only change needed is [setting channel_ id and payment_source_id to null](https://github.com/7fe2752182d43f856b49a802e36d597c78ae87b/nitro-sniper-enhanced/blob/e0da3524c1cace79eb25857f9469d838e56a4d6c/index.js#L335-L346). I don't have a live gift code to work on, so I'll keep my instance running with this patch for a while to see if the message still appears.
Many different snipers; [JS](https://github.com/5l1v3r1/Selfbot-JS/blob/0823eca9b272751025e48049aa86f03231e22ff4/Features/NitroAccepter.js#L7), [Golang](https://github.com/asdep1/leregleurdeconte1/blob/2bd02fc8dec7414babc6820d18012abef3e4de7f/main.go#L57), [Python](https://github.com/aaix/nitro-sniper/blob/50774016f6930a5471e8ee0b033932f5a26b04f4/bot.py#L33) use either null, None, or only fill in the channel_id with no additional code for payment_source_id.
One other sniper; [Golang](https://github.com/Vedza/NitroSniperGo/blob/69dfc0fa611b6c8127c11668a9ad47e6b47a16ec/sniper.go#L682) does have code for payment_source_id.

Sorry for the wall of text!

### CODE REVIEW

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
Reverted to draft because of this seemingly-new message appearing: 
`[Nitro Sniper] (ERROR) Tried to redeem code [x] but got error: Missing Access.`
From [a different sniper](https://github.com/noto-rious/Nitro.Self-V3/blob/65ca404119740e0fb7c0abd56a31e216e959cc8c/sniper.go#L633), they handle this message the same as an already-redeemed gift.

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
85f5fe5 handles `Missing Access` by marking it as already redeemed. Adds content-type and calculates content-length in the headers to fix `Payment source required`.
`[Already purchased](https://support.discord.com/hc/en-us/articles/360047412672-Get-3-months-of-Nitro-with-Xbox-Game-Pass-Ultimate#h_01EH66K9S2N9H557C2EXZ4WCNT)` + `New subscription required` is treated as an Xbox code (1 per account) and logs accordingly.
Ready to review and merge.

**Comment by GiorgioBrux** [comment]
Thanks!

**Pull request merged**
