### PR TITLE
Implement embeds 

### PR DESCRIPTION
**Pull request by 7fe2752182d43f856b49a802e36d597c78ae87b**
#19 
I'm not too experienced with coding, so it may look sloppy or not be performant. Feel free to modify. Here are some issues I wasn't able to resolve:

- [x] [embed.field does not push to codes (scope issue)](https://github.com/7fe2752182d43f856b49a802e36d597c78ae87b/nitro-sniper-enhanced/blob/a9c8a9c32aeb69de102c1613aafdb4306c4bf077/index.js#L125-L136)
- [x] The for loop (line 169) stops on the first Fake Code / Already Seen message, and doesn't parse other codes

I also converted `let codes` to `var codes` because line 128 didn't like it, not sure of the side-effects of this.

### CODE REVIEW

**Comment by GiorgioBrux** [comment]
Thanks a lot for the PR.

What's the deal with the 'Payment source required to redeem gift' thing?
If it isn't embeds-related just leave it alone and I will open an issue separately.

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
Hi, the 'Payment source required to redeem gift' is not related to embeds. It only shows with the addition of a9c8a9c and a5cc7dc which aren't in the master branch currently. I wasn't sure if that should be in a separate PR or an issue.

**Comment by GiorgioBrux** [comment]
Are you absolutely sure those 2 commits are the problem?
Also, can you be more specific about the issue? Unless I misunderstood and if it happens while redeeming, I guess it's a server-change by discord.

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
Sorry for the confusion, yes that error shows while redeeming. 
On your branch, if that error were to happen, nothing would be output.
```
if (err)
else if (res.body.message === '401: Unauthorized')
else if (res.body.message === "This gift has been redeemed already.")
else if ('subscription_plan' in res.body)
else if (res.body.message === "Unknown Gift Code")
```
The two commits show any other errors with redeeming. If the response isn't any of those (or is `Payment source required`), it won't log anything.

**Comment by GiorgioBrux** [comment]
Better your way then, good job for finding that error.
No need to tackle it further in this PR, I opened #23 

On a quick look, the embed part should be all right. If you are out of ideas on how to solve the embeds.field issue, I can give it a deeper look.

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
embed.field was supposed to be embed.field**s**, fixed in 5adb2d7 along with the regex for removing ) at the end of masked values in c23fe5c. Should be ready to merge.

**Comment by GiorgioBrux** [comment]
Thanks again!

**Pull request merged**
